var mongoose = require('mongoose');
var Campsite = require('./models/campsite')

// Connect to database
if (process.env.MONGODB_URI) {
  mongoose.connect(process.env.MONGODB_URI);
}
else {
  mongoose.connect('mongodb://localhost/waypoint');
}
mongoose.connection.on('error', function(err) {
  console.error('MongoDB connection error: ' + err);
  process.exit(-1);
  }
);
mongoose.connection.once('open', function() {
  console.log("Mongoose has connected to MongoDB!");
});

// our script will not exit until we have disconnected from the db.
function quit() {
  mongoose.disconnect();
  console.log('\nQuitting!');
}

// a simple error handler
function handleError(err) {
  console.log('ERROR:', err);
  quit();
  return err;
}

var data = [
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530145",
        "-facilityName": "A. H. STEPHENS STATE HISTORIC PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530145/0/80x53.jpg",
        "-latitude": "33.5633333",
        "-longitude": "-82.8966667",
        "-shortName": "C145",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71006",
        "-facilityName": "AMITY RECREATION AREA",
        "-faciltyPhoto": "/webphotos/NRSO/pid71006/0/80x53.jpg",
        "-latitude": "33.6461111",
        "-longitude": "-82.4719444",
        "-shortName": "AMI2",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71016",
        "-facilityName": "BALD RIDGE CREEK",
        "-faciltyPhoto": "/webphotos/NRSO/pid71016/0/80x53.jpg",
        "-latitude": "34.2038889",
        "-longitude": "-84.0861111",
        "-shortName": "BALR",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "75451",
        "-facilityName": "BIG HART (DAY-USE SHELTER)",
        "-faciltyPhoto": "/webphotos/NRSO/pid75451/0/80x53.jpg",
        "-latitude": "33.6172028",
        "-longitude": "-82.5130944",
        "-shortName": "BHAT",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71034",
        "-facilityName": "BIG HART CAMPGROUND",
        "-faciltyPhoto": "/webphotos/NRSO/pid71034/0/80x53.jpg",
        "-latitude": "33.6145806",
        "-longitude": "-82.5087472",
        "-shortName": "BIGH",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71037",
        "-facilityName": "BIG OAKS",
        "-faciltyPhoto": "/webphotos/NRSO/pid71037/0/80x53.jpg",
        "-latitude": "34.3402778",
        "-longitude": "-82.8327778",
        "-shortName": "BIGO",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530146",
        "-facilityName": "BLACK ROCK MOUNTAIN STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530146/0/80x53.jpg",
        "-latitude": "34.9094444",
        "-longitude": "-83.415",
        "-shortName": "C146",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71046",
        "-facilityName": "BOLDING MILL",
        "-faciltyPhoto": "/webphotos/NRSO/pid71046/0/80x53.jpg",
        "-latitude": "34.337925",
        "-longitude": "-83.9511444",
        "-shortName": "BOLD",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "138591",
        "-facilityName": "BOLDING MILL SHELTERS (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid138591/0/80x53.jpg",
        "-latitude": "34.3381139",
        "-longitude": "-83.9513778",
        "-shortName": "J591",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "138592",
        "-facilityName": "BUFORD DAM PARK SHELTERS (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid138592/0/80x53.jpg",
        "-latitude": "34.1524861",
        "-longitude": "-84.0615167",
        "-shortName": "F592",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530483",
        "-facilityName": "CHATTAHOOCHEE BEND",
        "-faciltyPhoto": "/webphotos/GA/pid530483/0/80x53.jpg",
        "-latitude": "33.4294444",
        "-longitude": "-84.9894444",
        "-shortName": "C483",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71088",
        "-facilityName": "CLARK CREEK NORTH",
        "-faciltyPhoto": "/webphotos/NRSO/pid71088/0/80x53.jpg",
        "-latitude": "34.0972222",
        "-longitude": "-84.6805556",
        "-shortName": "CLAN",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530148",
        "-facilityName": "CLOUDLAND CANYON STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530148/0/80x53.jpg",
        "-latitude": "34.4855556",
        "-longitude": "-85.2922222",
        "-shortName": "C148",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "135890",
        "-facilityName": "COOPER BRANCH No 2 DAY USE AREA (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid135890/0/80x53.jpg",
        "-latitude": "34.1717417",
        "-longitude": "-84.73465",
        "-shortName": "L890",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "135891",
        "-facilityName": "COOPER&apos;S FURNACE DAY USE AREA (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid135891/0/80x53.jpg",
        "-latitude": "34.1641556",
        "-longitude": "-84.7357083",
        "-shortName": "D891",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Riverfront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71105",
        "-facilityName": "COTTON HILL",
        "-faciltyPhoto": "/webphotos/NRSO/pid71105/0/80x53.jpg",
        "-latitude": "31.6744444",
        "-longitude": "-85.0641667",
        "-shortName": "COTD",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530149",
        "-facilityName": "CROOKED RIVER STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530149/0/80x53.jpg",
        "-latitude": "30.8413889",
        "-longitude": "-81.55",
        "-shortName": "C149",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530203",
        "-facilityName": "DODGE COUNTY PUBLIC FISHING AREA",
        "-faciltyPhoto": "/images/nophoto.jpg",
        "-latitude": "32.1578361",
        "-longitude": "-83.1337472",
        "-shortName": "C203",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71143",
        "-facilityName": "DOLL MT. CAMPGROUND",
        "-faciltyPhoto": "/webphotos/NRSO/pid71143/0/80x53.jpg",
        "-latitude": "34.6133333",
        "-longitude": "-84.6238889",
        "-shortName": "DOLL",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "531350",
        "-facilityName": "DON CARTER STATE PARK ",
        "-faciltyPhoto": "/webphotos/GA/pid531350/0/80x53.jpg",
        "-latitude": "34.3897222",
        "-longitude": "-83.7527778",
        "-shortName": "DCSP",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71148",
        "-facilityName": "DUCKETT MILL",
        "-faciltyPhoto": "/webphotos/NRSO/pid71148/0/80x53.jpg",
        "-latitude": "34.3081833",
        "-longitude": "-83.9313167",
        "-shortName": "DUCM",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71151",
        "-facilityName": "EASTBANK",
        "-faciltyPhoto": "/webphotos/NRSO/pid71151/0/80x53.jpg",
        "-latitude": "30.7180556",
        "-longitude": "-84.8511111",
        "-shortName": "EAS1",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530151",
        "-facilityName": "ELIJAH CLARK STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530151/0/80x53.jpg",
        "-latitude": "33.8538889",
        "-longitude": "-82.4033333",
        "-shortName": "C151",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71164",
        "-facilityName": "ELROD FERRY",
        "-faciltyPhoto": "/webphotos/NRSO/pid71164/0/80x53.jpg",
        "-latitude": "34.3625",
        "-longitude": "-82.8569444",
        "-shortName": "ELRO",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530153",
        "-facilityName": "F. D. ROOSEVELT STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530153/0/80x53.jpg",
        "-latitude": "32.8375",
        "-longitude": "-84.8155556",
        "-shortName": "C153",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530154",
        "-facilityName": "FLORENCE MARINA STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530154/0/80x53.jpg",
        "-latitude": "32.0908333",
        "-longitude": "-85.0430556",
        "-shortName": "C154",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530156",
        "-facilityName": "FORT MCALLISTER STATE HISTORIC PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530156/0/80x53.jpg",
        "-latitude": "31.8905556",
        "-longitude": "-81.1958333",
        "-shortName": "C156",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530158",
        "-facilityName": "FORT MOUNTAIN STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530158/0/80x53.jpg",
        "-latitude": "34.7611111",
        "-longitude": "-84.6994444",
        "-shortName": "C158",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530159",
        "-facilityName": "FORT YARGO STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530159/0/80x53.jpg",
        "-latitude": "33.9716667",
        "-longitude": "-83.7272222",
        "-shortName": "C159",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "135991",
        "-facilityName": "GALT&apos;S FERRY DAY USE AREA (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid135991/0/80x53.jpg",
        "-latitude": "34.1311278",
        "-longitude": "-84.6448194",
        "-shortName": "F991",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530160",
        "-facilityName": "GENERAL COFFEE STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530160/0/80x53.jpg",
        "-latitude": "31.5263889",
        "-longitude": "-82.7608333",
        "-shortName": "C160",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530161",
        "-facilityName": "GEORGE L. SMITH STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530161/0/80x53.jpg",
        "-latitude": "32.5619444",
        "-longitude": "-82.1105556",
        "-shortName": "C161",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530163",
        "-facilityName": "GEORGIA VETERANS MEMORIAL STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530163/0/80x53.jpg",
        "-latitude": "31.9577778",
        "-longitude": "-83.9036111",
        "-shortName": "C163",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71181",
        "-facilityName": "GILL POINT",
        "-faciltyPhoto": "/webphotos/NRSO/pid71181/0/80x53.jpg",
        "-latitude": "33.9416667",
        "-longitude": "-82.5944444",
        "-shortName": "GILL",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530164",
        "-facilityName": "GORDONIA ALATAMAHA STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530164/0/80x53.jpg",
        "-latitude": "32.0861111",
        "-longitude": "-82.1208333",
        "-shortName": "C164",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530165",
        "-facilityName": "HAMBURG STATE OUTDOOR RECREATION AREA",
        "-faciltyPhoto": "/webphotos/GA/pid530165/0/80x53.jpg",
        "-latitude": "33.205",
        "-longitude": "-82.7769444",
        "-shortName": "C165",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530166",
        "-facilityName": "HARD LABOR CREEK STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530166/0/80x53.jpg",
        "-latitude": "33.6547222",
        "-longitude": "-83.5968472",
        "-shortName": "C166",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530168",
        "-facilityName": "HIGH FALLS STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530168/0/80x53.jpg",
        "-latitude": "33.1811111",
        "-longitude": "-84.0158333",
        "-shortName": "C168",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71210",
        "-facilityName": "HOLIDAY",
        "-faciltyPhoto": "/webphotos/NRSO/pid71210/0/80x53.jpg",
        "-latitude": "33.0261111",
        "-longitude": "-85.1788889",
        "-shortName": "HOL1",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530170",
        "-facilityName": "INDIAN SPRINGS STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530170/0/80x53.jpg",
        "-latitude": "33.2438889",
        "-longitude": "-83.9308333",
        "-shortName": "C170",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530171",
        "-facilityName": "JAMES H.(SLOPPY) FLOYD STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530171/0/80x53.jpg",
        "-latitude": "34.4397222",
        "-longitude": "-85.3391667",
        "-shortName": "C171",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530175",
        "-facilityName": "KOLOMOKI MOUNDS STATE HISTORIC PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530175/0/80x53.jpg",
        "-latitude": "31.4713889",
        "-longitude": "-84.9252778",
        "-shortName": "C175",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71244",
        "-facilityName": "LAKE SPRINGS",
        "-faciltyPhoto": "/webphotos/NRSO/pid71244/0/80x53.jpg",
        "-latitude": "33.665925",
        "-longitude": "-82.2292972",
        "-shortName": "LASC",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "75347",
        "-facilityName": "LAKE WINFIELD SCOTT REC",
        "-faciltyPhoto": "/webphotos/NRSO/pid75347/0/80x53.jpg",
        "-latitude": "34.7403333",
        "-longitude": "-83.892",
        "-shortName": "LWSC",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "138542",
        "-facilityName": "LANIER PARK SHELTER (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid138542/0/80x53.jpg",
        "-latitude": "34.15365",
        "-longitude": "-84.0556833",
        "-shortName": "F542",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530177",
        "-facilityName": "LAURA S. WALKER STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530177/0/80x53.jpg",
        "-latitude": "31.1430556",
        "-longitude": "-82.2163889",
        "-shortName": "C177",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "138593",
        "-facilityName": "LITTLE HALL SHELTER (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid138593/0/80x53.jpg",
        "-latitude": "34.3139806",
        "-longitude": "-83.9444417",
        "-shortName": "F593",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530179",
        "-facilityName": "MAGNOLIA SPRINGS STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530179/0/80x53.jpg",
        "-latitude": "32.8866667",
        "-longitude": "-81.9555556",
        "-shortName": "C179",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71288",
        "-facilityName": "MCKASKEY CREEK CG",
        "-faciltyPhoto": "/webphotos/NRSO/pid71288/0/80x53.jpg",
        "-latitude": "34.19",
        "-longitude": "-84.7180556",
        "-shortName": "MCKA",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71289",
        "-facilityName": "MCKINNEY CAMPGROUND",
        "-faciltyPhoto": "/webphotos/NRSO/pid71289/0/80x53.jpg",
        "-latitude": "34.1069444",
        "-longitude": "-84.6955556",
        "-shortName": "MCKI",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530180",
        "-facilityName": "MISTLETOE STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530180/0/80x53.jpg",
        "-latitude": "33.6416667",
        "-longitude": "-82.3680556",
        "-shortName": "C180",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530181",
        "-facilityName": "MOCCASIN CREEK STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530181/0/80x53.jpg",
        "-latitude": "34.8458333",
        "-longitude": "-83.5872222",
        "-shortName": "C181",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "75484",
        "-facilityName": "MORGANTON POINT",
        "-faciltyPhoto": "/webphotos/NRSO/pid75484/0/80x53.jpg",
        "-latitude": "34.875",
        "-longitude": "-84.25",
        "-shortName": "MGTP",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "75351",
        "-facilityName": "NANCYTOWN GROUP CAMPGROUND",
        "-faciltyPhoto": "/webphotos/NRSO/pid75351/0/80x53.jpg",
        "-latitude": "34.4988889",
        "-longitude": "-83.4836111",
        "-shortName": "NANC",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71321",
        "-facilityName": "OLD FEDERAL",
        "-faciltyPhoto": "/webphotos/NRSO/pid71321/0/80x53.jpg",
        "-latitude": "34.2222222",
        "-longitude": "-83.9494444",
        "-shortName": "OLDF",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71327",
        "-facilityName": "OLD HWY 41 NO 3",
        "-faciltyPhoto": "/webphotos/NRSO/pid71327/0/80x53.jpg",
        "-latitude": "34.0883333",
        "-longitude": "-84.7105556",
        "-shortName": "OHW3",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530183",
        "-facilityName": "PANOLA MOUNTAIN STATE CONSERVATION PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530183/0/80x53.jpg",
        "-latitude": "33.6322222",
        "-longitude": "-84.1705556",
        "-shortName": "C183",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71343",
        "-facilityName": "PAYNE CAMPGROUND-ALLATOONA LAKE",
        "-faciltyPhoto": "/webphotos/NRSO/pid71343/0/80x53.jpg",
        "-latitude": "34.1208333",
        "-longitude": "-84.5791667",
        "-shortName": "PAYN",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71344",
        "-facilityName": "PAYNES CREEK(HARTWELL LAKE)",
        "-faciltyPhoto": "/webphotos/NRSO/pid71344/0/80x53.jpg",
        "-latitude": "34.4791667",
        "-longitude": "-82.9752778",
        "-shortName": "PAYC",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71348",
        "-facilityName": "PETERSBURG",
        "-faciltyPhoto": "/webphotos/NRSO/pid71348/0/80x53.jpg",
        "-latitude": "33.6619444",
        "-longitude": "-82.2608333",
        "-shortName": "PETB",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530184",
        "-facilityName": "PICKETT&apos;S MILL BATTLEFIELD STATE HISTORIC SITE",
        "-faciltyPhoto": "/webphotos/GA/pid530184/0/80x53.jpg",
        "-latitude": "33.9847222",
        "-longitude": "-84.7469444",
        "-shortName": "C184",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "75353",
        "-facilityName": "POCKET PICNIC SHELTER",
        "-faciltyPhoto": "/webphotos/NRSO/pid75353/0/80x53.jpg",
        "-latitude": "34.5841667",
        "-longitude": "-85.0811111",
        "-shortName": "POCK",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71363",
        "-facilityName": "POPLAR SPRINGS",
        "-faciltyPhoto": "/webphotos/NRSO/pid71363/0/80x53.jpg",
        "-latitude": "34.5205556",
        "-longitude": "-82.0877778",
        "-shortName": "POPL",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530185",
        "-facilityName": "PROVIDENCE CANYON STATE OUTDOOR RECREATION AREA",
        "-faciltyPhoto": "/webphotos/GA/pid530185/0/80x53.jpg",
        "-latitude": "32.0655556",
        "-longitude": "-84.9205556",
        "-shortName": "C185",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71370",
        "-facilityName": "R SHAEFER HEARD",
        "-faciltyPhoto": "/webphotos/NRSO/pid71370/0/80x53.jpg",
        "-latitude": "32.9272222",
        "-longitude": "-85.1638889",
        "-shortName": "RSH1",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530364",
        "-facilityName": "RED TOP MOUNTAIN STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530364/0/80x53.jpg",
        "-latitude": "34.1475",
        "-longitude": "-84.7072222",
        "-shortName": "C364",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530186",
        "-facilityName": "REED BINGHAM STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530186/0/80x53.jpg",
        "-latitude": "31.1666667",
        "-longitude": "-83.5477778",
        "-shortName": "C186",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530188",
        "-facilityName": "RICHARD B. RUSSELL STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530188/0/80x53.jpg",
        "-latitude": "34.1666667",
        "-longitude": "-82.7455556",
        "-shortName": "C188",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71378",
        "-facilityName": "RIDGE ROAD",
        "-faciltyPhoto": "/webphotos/NRSO/pid71378/0/80x53.jpg",
        "-latitude": "33.68",
        "-longitude": "-82.2586111",
        "-shortName": "RIDG",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "136091",
        "-facilityName": "RIVERSIDE PARK DAY USE AREA (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid136091/0/80x53.jpg",
        "-latitude": "34.1609528",
        "-longitude": "-84.7417",
        "-shortName": "D091",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Riverfront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71409",
        "-facilityName": "SAWNEE",
        "-faciltyPhoto": "/images/nophoto.jpg",
        "-latitude": "34.1766667",
        "-longitude": "-84.0752778",
        "-shortName": "SAWN",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530190",
        "-facilityName": "SEMINOLE STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530190/0/80x53.jpg",
        "-latitude": "30.8055556",
        "-longitude": "-84.8752778",
        "-shortName": "C190",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530191",
        "-facilityName": "SKIDAWAY ISLAND STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530191/0/80x53.jpg",
        "-latitude": "31.9583333",
        "-longitude": "-81.0525",
        "-shortName": "C191",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530192",
        "-facilityName": "SMITHGALL WOODS",
        "-faciltyPhoto": "/webphotos/GA/pid530192/0/80x53.jpg",
        "-latitude": "34.6919444",
        "-longitude": "-83.7672222",
        "-shortName": "C192",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530194",
        "-facilityName": "STEPHEN C. FOSTER STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530194/0/80x53.jpg",
        "-latitude": "30.8269444",
        "-longitude": "-82.3619444",
        "-shortName": "C194",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71440",
        "-facilityName": "SWEETWATER CG",
        "-faciltyPhoto": "/webphotos/NRSO/pid71440/0/80x53.jpg",
        "-latitude": "34.1944444",
        "-longitude": "-84.5788889",
        "-shortName": "SWEE",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530195",
        "-facilityName": "SWEETWATER CREEK STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530195/0/80x53.jpg",
        "-latitude": "33.7583333",
        "-longitude": "-84.6358333",
        "-shortName": "C195",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "135992",
        "-facilityName": "SWEETWATER DAY USE AREA (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid135992/0/80x53.jpg",
        "-latitude": "34.1983",
        "-longitude": "-84.5756833",
        "-shortName": "D992",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530196",
        "-facilityName": "TALLULAH GORGE STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530196/0/80x53.jpg",
        "-latitude": "34.725",
        "-longitude": "-83.37",
        "-shortName": "C196",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "138644",
        "-facilityName": "THOMPSON CREEK PARK SHELTER (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid138644/0/80x53.jpg",
        "-latitude": "34.3520917",
        "-longitude": "-84.0202278",
        "-shortName": "C644",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530198",
        "-facilityName": "TUGALOO STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530198/0/80x53.jpg",
        "-latitude": "34.4947222",
        "-longitude": "-83.0677778",
        "-shortName": "C198",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "138492",
        "-facilityName": "UPPER OVERLOOK SHELTERS (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid138492/0/80x53.jpg",
        "-latitude": "34.15755",
        "-longitude": "-84.0721417",
        "-shortName": "B492",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71467",
        "-facilityName": "UPPER STAMP CREEK CG",
        "-faciltyPhoto": "/webphotos/NRSO/pid71467/0/80x53.jpg",
        "-latitude": "34.2027778",
        "-longitude": "-84.6766667",
        "-shortName": "UPSC",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "138543",
        "-facilityName": "VAN PUGH NORTH PARK SHELTER (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid138543/0/80x53.jpg",
        "-latitude": "34.1872056",
        "-longitude": "-83.9810833",
        "-shortName": "B543",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "94168",
        "-facilityName": "VAN PUGH SOUTH CAMPGROUND",
        "-faciltyPhoto": "/webphotos/NRSO/pid94168/0/80x53.jpg",
        "-latitude": "34.1844444",
        "-longitude": "-83.9905556",
        "-shortName": "F168",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Oceanfront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530200",
        "-facilityName": "VICTORIA BRYANT STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530200/0/80x53.jpg",
        "-latitude": "34.2963889",
        "-longitude": "-83.1597222",
        "-shortName": "C200",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71471",
        "-facilityName": "VICTORIA CAMPGROUND",
        "-faciltyPhoto": "/webphotos/NRSO/pid71471/0/80x53.jpg",
        "-latitude": "34.1513889",
        "-longitude": "-84.6194444",
        "-shortName": "VICT",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "Y",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530201",
        "-facilityName": "VOGEL STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530201/0/80x53.jpg",
        "-latitude": "34.7319444",
        "-longitude": "-83.9169444",
        "-shortName": "C201",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71483",
        "-facilityName": "WATSADLER",
        "-faciltyPhoto": "/webphotos/NRSO/pid71483/0/80x53.jpg",
        "-latitude": "34.3438889",
        "-longitude": "-82.8413889",
        "-shortName": "WATS",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "GA",
        "-contractType": "STATE",
        "-facilityID": "530202",
        "-facilityName": "WATSON MILL BRIDGE STATE PARK",
        "-faciltyPhoto": "/webphotos/GA/pid530202/0/80x53.jpg",
        "-latitude": "34.0277778",
        "-longitude": "-83.0727778",
        "-shortName": "C202",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "138594",
        "-facilityName": "WEST BANK PARK SHELTERS (GA)",
        "-faciltyPhoto": "/webphotos/NRSO/pid138594/0/80x53.jpg",
        "-latitude": "34.1676278",
        "-longitude": "-84.0729194",
        "-shortName": "D594",
        "-sitesWithAmps": "N",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "N",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71493",
        "-facilityName": "WEST DAM",
        "-faciltyPhoto": "/webphotos/NRSO/pid71493/0/80x53.jpg",
        "-latitude": "33.6608333",
        "-longitude": "-82.1997222",
        "-shortName": "WESD",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71499",
        "-facilityName": "WHITETAIL RIDGE",
        "-faciltyPhoto": "/webphotos/NRSO/pid71499/0/80x53.jpg",
        "-latitude": "33.0222222",
        "-longitude": "-85.1916667",
        "-shortName": "WHRI",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-sitesWithWaterfront": "Lakefront",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "75239",
        "-facilityName": "WILLIS KNOB HORSE CAMP",
        "-faciltyPhoto": "/webphotos/NRSO/pid75239/0/80x53.jpg",
        "-latitude": "34.8994444",
        "-longitude": "-83.2225",
        "-shortName": "KNOB",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "N",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71506",
        "-facilityName": "WINFIELD",
        "-faciltyPhoto": "/webphotos/NRSO/pid71506/0/80x53.jpg",
        "-latitude": "33.6519444",
        "-longitude": "-82.4219444",
        "-shortName": "WINF",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      },
      {
        "-availabilityStatus": "N",
        "-contractID": "NRSO",
        "-contractType": "FEDERAL",
        "-facilityID": "71508",
        "-facilityName": "WOODRING CAMPGROUND",
        "-faciltyPhoto": "/webphotos/NRSO/pid71508/0/80x53.jpg",
        "-latitude": "34.6705556",
        "-longitude": "-84.55",
        "-shortName": "WOO1",
        "-sitesWithAmps": "Y",
        "-sitesWithPetsAllowed": "Y",
        "-sitesWithSewerHookup": "N",
        "-sitesWithWaterHookup": "Y",
        "-state": "GA"
      }
      ]

console.log('removing old campsites...');
Campsite.remove({})
.then(function() {
  console.log('old campsites removed');
  console.log('creating some new campsites...');

  // var campsites = [new Campsite({}), new Campsite({})]
  var campsites = [];

for(var i = 0; i < data.length; i++)
{
  var cs = new Campsite({
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [ data[i]['-longitude'], data[i]['-latitude'] ]
    },
    properties: {
      contractID: data[i]['-contractID'],
      contractType: data[i]['-contractType'],
      facilityID: data[i]['-facilityID'],
      title: data[i]['-facilityName'],
      petsAllowed: data[i]['-sitesWithPetsAllowed'],
      waterFront: data[i]['-sitesWithWaterfront'] ? data[i]['-sitesWithWaterfront'] : '',
      sitesWithAmps: data[i]['-sitesWithAmps'],
      sitesWithSewerHookerup: data[i]['-sitesWithSewerHookup'],
      sitesWithWaterHookup: data[i]['-sitesWithWaterHookup'],
      address: {
        state: data[i]['-state'],
      }
    }

  });
  campsites.push(cs);
}
  return Campsite.create(campsites);
})
.then(function(savedCampsites) {
  console.log('Just saved', savedCampsites.length, 'campsites.');
  return Campsite.find({});
})
.then(function(allCampsites) {
  console.log('Printing all campsites:');
  allCampsites.forEach(function(campsite) {
    console.log(campsite);
  });
  quit();
});
